name: "test itself"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for deploy'
        required: true
      env:
        description: 'Env for deploy (prod, prod-au, rc, hf, stage)'
        required: true

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - name: "Get tag name"
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.env }}" >> ${GITHUB_ENV}
          echo "RELEASE_TAG=${{ github.event.inputs.tag }}" >> ${GITHUB_ENV}
      - name: "Check out repository" 
        uses: actions/checkout@v2
      - uses: ./
        with:
          tag: ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
