name: "test itself"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for deploy'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository" 
        uses: actions/checkout@v2
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.inputs.tag }}
